services:
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mydb
    ports:
      - "5000:3306"

  nginx:
    image: nginx
    container_name: nginx-container
    depends_on:
      - mysql
    ports:
      - "8080:80"